name: vae

defaults:
  - encoder: convolutional64
  - decoder: convolutional64
  - action_selection: random

_target_: agents.VAE.VAE

# Miscellaneous
n_states: 10
lr: 0.0001
queue_capacity: 50000
tensorboard_dir: "${oc.env:DATA_DIRECTORY}/runs/${agent.name}_${env.name}_${seed}"

# Beta scheduling
beta: 1.0
beta_starting_step: 0
beta_rate: 0.0000
n_steps_beta_reset: 10000000000
